Add Fine
fmerian/launch-weeks pull request #2
Opened 2023-09-07 11:10 UTC by jonathanhar

We had an issue with our launch previous week, so we postponed in one week. Sorry for the inconvenience.

2023-09-07 14:44 UTC, fmerian commented
> We had an issue with our launch previous week, so we postponed in one week. Sorry for the inconvenience.

oh sorry to read that, @jonathanhar! when do you plan to tease the launch week? would prefer to add context, i.e. a link to a post/page that does announce the event. 

keep up your great work, thanks!

2023-09-07 14:45 UTC, fmerian requested changes
> We had an issue with our launch previous week, so we postponed in one week. Sorry for the inconvenience.

oh sorry to read that, @jonathanhar! when do you plan to tease the launch week? would prefer to add context, i.e. a link to a post/page that does announce the event. 

keep up your great work, thanks!

2023-09-07 14:49 UTC, HaJongler commented
We will tease it on Sunday, and Monday is the big go day 🚀 
I'll ping here when the tease is out so we can merge, meanwhile I'll convert to draft.
Thanks for the kindness!

2023-09-07 14:54 UTC, fmerian commented
awesome. thanks!

2023-09-11 07:56 UTC, fmerian approved these changes
LGTM. thanks, @jonathanhar, and enjoy your launch week!

2023-09-11 07:56 UTC, merged